# Generated by Django 4.2.7 on 2025-11-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_info',
            old_name='domain',
            new_name='industry',
        ),
        migrations.AddField(
            model_name='company_info',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
